// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5MXT-DsuNF6o6IPOQKDn9bCMzBApj0-g',
    appId: '1:688239089075:web:b0259d0ab8205df3c667c6',
    messagingSenderId: '688239089075',
    projectId: 'articly-save',
    authDomain: 'articly-save.firebaseapp.com',
    storageBucket: 'articly-save.firebasestorage.app',
    measurementId: 'G-H6K7CRYR0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Ebj3eTTTrqtUIBT_6vJvuooiIKecnaw',
    appId: '1:688239089075:android:ef4c353055f204e7c667c6',
    messagingSenderId: '688239089075',
    projectId: 'articly-save',
    storageBucket: 'articly-save.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKvjR8U_Ld42fYwSCNcKj_ccJA6g3IRyQ',
    appId: '1:688239089075:ios:1f593ebef7bdfd14c667c6',
    messagingSenderId: '688239089075',
    projectId: 'articly-save',
    storageBucket: 'articly-save.firebasestorage.app',
    iosClientId: '688239089075-dge21kbpu2rvhev39ui413f1ng7a4k88.apps.googleusercontent.com',
    iosBundleId: 'com.example.articly',
  );
}
